### ISSUE TITLE
mapping from nested json with conditionals

### ISSUE THREAD

**Issue by hmenager** [caltechlibrary/convert_codemeta#2]
mapping from bio.tools json requires for some terms to support conditional expressions, a little bit like in xpath. For example, 

```
link[type='repository']/url
```

to find `codeRepository` in https://github.com/caltechlibrary/convert_codemeta/blob/master/tests/integron_finder.biotools.json

**Comment by tmorrell** [comment]
This is supported in v0.0.1. You can add any additional conditional expressions to a new issue (the current bio.tools codemeta example is at https://github.com/caltechlibrary/convert_codemeta/blob/master/tests/codemeta_biotools.json, but there are more fields to add)
